addon-name: "BetterBags - Openable Items"
addon-description: "BetterBags plugin for openable containers"
urls:
  curseforge: "https://www.curseforge.com/wow/addons/betterbags-openable"
  wago: "https://addons.wago.io/addons/aNevMb62"
  discord: "https://discord.gg/Qc9TRBv"
